# Generated by Django 3.2.11 on 2022-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='properties',
            field=models.CharField(blank=True, choices=[(1, 'aisle seat'), (2, 'front row seat'), (3, 'high seat')], default=None, max_length=50),
        ),
    ]
