# Generated by Django 3.2.11 on 2022-01-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_alter_seat_properties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('section', 'rank', 'seat_number', 'row')},
        ),
    ]
