# # Generated by Django 3.2.11 on 2022-01-05 18:29
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     initial = True
#
#     dependencies = [
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='Seat',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('section', models.CharField(choices=[(1, 'main hall'), (2, '1st balcony'), (3, '2nd balcony')], default=None, max_length=11)),
#                 ('rank', models.CharField(choices=[(1, '1st rank'), (2, '2nd rank'), (3, '3th rank')], default=None, max_length=8)),
#                 ('seat_number', models.IntegerField()),
#                 ('is_sold', models.BooleanField(default=False)),
#                 ('properties', models.CharField(blank=True, choices=[(1, 'aisle seat'), (2, 'front row seat'), (3, 'high seat')], default=None, max_length=15)),
#                 ('row', models.CharField(max_length=2)),
#             ],
#         ),
#     ]
